# Generated by Django 4.2 on 2023-05-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login_And_SLogin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertable",
            name="register_time",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
