# Generated by Django 4.2 on 2023-05-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login_And_SLogin", "0002_usertable_register_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertable",
            name="register_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
