# Generated by Django 4.2.1 on 2023-06-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_And_SLogin', '0004_alter_usertable_options_alter_usertable_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
