# Generated by Django 4.2.1 on 2023-08-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='地名')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
                ('level', models.CharField(max_length=2, verbose_name='等级')),
                ('content', models.TextField(verbose_name='介绍内容')),
            ],
            options={
                'verbose_name': '攻略',
                'verbose_name_plural': '攻略',
                'db_table': 'strategy_tb',
            },
        ),
    ]
