# Generated by Django 4.2.1 on 2023-08-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='img_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='图片路径'),
        ),
    ]
