# Generated by Django 4.2.1 on 2023-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_img_url_alter_article_publish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.IntegerField(default=1694521960, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.IntegerField(default=1694521960, verbose_name='评论时间'),
        ),
    ]
